version: '3'

networks:
  proxy:
    name: proxy

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    labels: 
      - "traefik.enable=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy    

  auth:
    image: juno941030/simol-auth:latest
    labels:
      - "traefik.http.middlewares.simol-auth.forwardauth.address=http://auth:8080/auth"
    environment:
      - TZ=Asia/Seoul
    networks:
      - proxy
      
  back:
    image: juno941030/simol-back:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simol-back.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.simol-back.middlewares=simol-auth"
    environment:
      - TZ=Asia/Seoul
    networks:
      - proxy